version: "3.8"
services:
  backend-flask:
    environment:
      CONNECTION_URL: "${PROD_CONNECTION_URL}"
      FRONTEND_URL: "http://localhost:3000"
      BACKEND_URL: "http://localhost:4567"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_COGNITO_USER_POOL_ID: "us-east-2_RD0sgfmW3"
      AWS_COGNITO_USER_POOL_CLIENT_ID: "7uebi1s2gcc6ijmk5latmgnv4p" 
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
  frontend-flask:
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:4567"
      REACT_APP_AWS_PROJECT_REGION: "${AWS_DEFAULT_REGION}"
      REACT_APP_AWS_COGNITO_REGION: "${AWS_DEFAULT_REGION}"
      REACT_APP_AWS_USER_POOLS_ID: "us-east-2_RD0sgfmW3"
      REACT_APP_CLIENT_ID: "7uebi1s2gcc6ijmk5latmgnv4p"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
  # dynamodb-local:
  #   # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volume-lack-permissions-unable-to-open-databa
  #   # We needs to add user:root to get this working
  #   user: root
  #   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
  #   image: "amazon/dynamodb-local:latest"
  #   container_name: dynamodb-local
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - "./docker/dynamodb:/home/dynamodblocal/data"
  #   working_dir: /home/dynamodblocal
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

# name the flag is a hack to change the default prepend foldeer
# name when outputting the image names
networks:
  internal-network:
    driver: bridge
    name: crudder

volumes: 
  db:
    driver: local
